version: "2"
services:
  nginx:
    image: openresty/openresty
    container_name: bugzhang-blog
    ports:
      - 80:80
    volumes:
      - ./public/:/usr/share/nginx/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    command: /bin/bash -c "nginx -g 'daemon off;'"
    restart: always
    mem_limit: 500M
